OTC-800: modular IMIS: renewing of free enrolment policies doesn't work
openimis/openimis-fe-policy_js pull request #49
Opened 2023-05-02 14:43 UTC by hirensoni913

https://openimis.atlassian.net/browse/OTC-800

Fixed the issue when selecting an officer start date of the policy becomes null.

2023-05-15 08:15 UTC, delcroip commented
@dborowiecki @hirensoni913  can you check why the code you commented was put there in the first place ?

2023-05-25 14:03 UTC, dragos-dobre requested changes

2023-05-25 14:03 UTC, dragos-dobre commented on src/components/PolicyForm.js
> +        // ,
Remove commented code.

2023-06-23 12:29 UTC, hirensoni913 commented
> 

@dborowiecki This block of code was duplicated

2023-06-23 12:31 UTC, hirensoni913 commented on src/components/PolicyForm.js
> +        // ,
Done

2023-07-06 09:29 UTC, delcroip approved these changes

2023-07-06 09:30 UTC, merged